# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  buildConfiguration: Release
  buildPlatform: Any CPU
  coreSolution: 'src\FreshMvvmTemplate\FreshMvvmTemplate.sln'
  coreCSProj: 'src\FreshMvvm\*.csproj'

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: VSBuild@1
  displayName: Nuget Restore
  inputs:
    solution: '$(coreSolution)'
    configuration: '$(buildConfiguration)'
    msbuildArgs: '/t:Restore'


